# Generated by Django 4.2.7 on 2023-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociclistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('solicitud', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
