# Generated by Django 4.2.7 on 2023-11-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motociclistas', '0002_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
