# Generated by Django 4.2.7 on 2023-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociclistas', '0003_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
